package Vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import Modelo.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Modelo.Sesion;

public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Menu
     */
    public Login() {
        initComponents(); }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        btnIniciarSesion.setText("INICIAR SESION");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        jLabel3.setText("EVENT MANAGER");

        jLabel4.setText("gestion de eventos y terrazas");

        jLabel5.setText("Acceso exclusivo para personal autorizado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel5)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

    // Se obtienen los datos escritos por el usuario
    String usuario = txtUsuario.getText().trim();
    String password = txtPassword.getText().trim();

    // Validación cuando los dos campos están vacíos
    if (usuario.isEmpty() && password.isEmpty()) {

        JOptionPane.showMessageDialog(this,"Ingrese el usuario y la contraseña.","Campos vacíos",JOptionPane.WARNING_MESSAGE);

        txtUsuario.requestFocus();
        return;
    }

    // Validación cuando solamente falta el usuario
    if (usuario.isEmpty()) {

        JOptionPane.showMessageDialog(this,"Ingrese el nombre de usuario.", "Usuario vacío",JOptionPane.WARNING_MESSAGE);

        txtUsuario.requestFocus();
        return;
    }

    // Validación cuando solamente falta la contraseña
    if (password.isEmpty()) {

        JOptionPane.showMessageDialog(this,"Ingrese la contraseña.","Contraseña vacía",JOptionPane.WARNING_MESSAGE );

        txtPassword.requestFocus();
        return;
    }

    // Se crea un objeto de la clase Conexion
    Conexion objconec = new Conexion();

    // Se intenta establecer la conexión con PostgreSQL
    Connection conexion = objconec.conectar();

    // Se verifica si la conexión falló
    if (conexion == null) {

        JOptionPane.showMessageDialog(this, "No se pudo conectar con la base de datos.\n" + "Verifique que PostgreSQL esté encendido.","Error de conexión",JOptionPane.ERROR_MESSAGE);

        return;
    }

    // Consulta para buscar un usuario con las credenciales ingresadas
 String sql = "SELECT * FROM usuarios "+ "WHERE usuario = ? " + "AND password = ? " + "AND estado = 'Activo'";

    try {

        // Se prepara la consulta SQL
        PreparedStatement PS = conexion.prepareStatement(sql);

        // Se colocan los datos en los signos de interrogación
        PS.setString(1, usuario);
        PS.setString(2, password);

        // Se ejecuta la consulta
        ResultSet RS = PS.executeQuery();

      // Si se encontró un usuario activo con esas credenciales
if (RS.next()) {

    // Guardamos en la sesión los datos del usuario
    Sesion.idUsuario = RS.getInt("id_usuario");
    Sesion.nombre = RS.getString("nombre");
    Sesion.usuario = RS.getString("usuario");
    Sesion.rol = RS.getString("rol");

    // Mensaje de bienvenida
    JOptionPane.showMessageDialog( this, "Bienvenido " + Sesion.nombre + ".", "Inicio de sesión correcto",JOptionPane.INFORMATION_MESSAGE);

    // Abrimos el menú principal
    MenuPrincipal objmenu = new MenuPrincipal();

    objmenu.setLocationRelativeTo(null);
    objmenu.setVisible(true);

    // Cerramos el Login
    this.dispose();

} else {

    JOptionPane.showMessageDialog(
            this,
            "Usuario o contraseña incorrectos,\n"
            + "o la cuenta se encuentra inactiva.",
            "Acceso denegado",
            JOptionPane.ERROR_MESSAGE
    );

    // Limpiamos la contraseña
    txtPassword.setText("");

    // Colocamos el cursor en la contraseña
    txtPassword.requestFocus();
}

        // Se cierran los objetos utilizados
        RS.close();
        PS.close();
        conexion.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Ocurrió un error al iniciar sesión.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        // El error completo aparecerá en Output de NetBeans
        System.out.println("Error en el Login: " + e.getMessage());
    }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}